# =====================================================
# Data displayed on the Home (About Me) page.
#
# 💡 Tip for Images / Logo:
# You can use either:
# 1. A full URL (e.g., https://example.com/logo.png)
# 2. A local file placed under /public/images/ and referenced with "/" (e.g., "/images/logo.png")
# =====================================================

# =====================================================
# 👤 Personal Information
# =====================================================

profile:
  name: "Jeffrey Yu"
  headline: "Student @ EPFL"
  email: "jeffreyyu880@gmail.com"
  location: null
  profileImage: "/public/images/headshot.jpg"

  links:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/[your-linkedin]"
      icon:
        name: "FaLinkedin"
        package: "react-icons/fa6"

    - name: "Résumé"
      url: "/pdf/sample-resume.pdf"
      icon:
        name: "FaRegIdBadge"
        package: "react-icons/fa6"

    - name: "Github"
      url: "https://github.com/[your-github]"
      icon:
        name: "FaGithub"
        package: "react-icons/fa6"

  # you can use HTML syntax here (e.g. <br/>, <a>, <strong>, ...)
  biography: |
    Hi! I'm <strong>Jeffrey Yu</strong>, a <em>Software Engineer</em> passionate about <em>Robotics and Machine Learning</em>. Currently, I work as <em>[current role]</em> at <em>[organization]</em>, where I <em>[briefly describe your work or mission]</em>. 
    With a background in <em>[academic or professional background]</em>, I've developed strong interests in <em>[key interests or specialties]</em> and have contributed to projects like <i>[example project]</i> and <i>[another example]</i>, all focused on <em>[broader goal or impact]</em>.
    <div class="my-2"></div>
    Outside of work, I enjoy <em>swimming, tennis, guitar, and reading</em>, which inspire creativity and keep me energized. Thanks for visiting! Feel free to <a href="mailto:[jeffreyyu880@gmail.com]" target="_blank" rel="noopener noreferrer">reach out</a> to connect.

# # =====================================================
# # 🎓 Education Section
# # =====================================================

education:
  - degree: "M.S. in Robotics and Machine Learning"
    school: "EPFL"
    years: "2023 - 2026"
    logo: "/images/epfl_logo.png"

  - degree: "B.S. in Computer Computer Engineering"
    school: "Georgia Institute of Technology"
    years: "2019 - 2023"
    logo: "/images/GT_logo.png"

# # =====================================================
# # 💼 Work Experience Section
# # =====================================================

workExperience:
  - title: "Machine Learning Engineering Intern"
    company: "Logitech"
    years: "September 2025 - February 2026"
    logo: "/images/logitech_logo.svg"

  - title: "Software Engineering Intern"
    company: "Garmin"
    years: "May 2023 - August 2023"
    logo: "/images/garmin_logo.svg"

  - title: "Software Engineering Intern"
    company: "Commscope"
    years: "May 2022 - August 2022"
    logo: "/images/garmin_logo.svg"

  - title: "Mechanical Engineering Intern"
    company: "University of Florida Startup"
    years: "November 2019 - March 2021"
    logo: "/images/garmin_logo.svg"

# # =====================================================
# # 🛠️ Skills Section
# # =====================================================

skills:
  Programming:
    - name: "C++"
      logo: "https://upload.wikimedia.org/wikipedia/commons/1/18/ISO_C%2B%2B_Logo.svg"
      proficiency: "Experienced"
      description: null

    - name: "Python"
      logo: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg"
      proficiency: Experienced
      description: null

    - name: "C"
      logo: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg"
      proficiency: Fluent
      description: null

    - name: "Matlab"
      logo: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg"
      proficiency: Fluent
      description: null

  Machine Learning:
    - name: "PyTorch"
      logo: "https://upload.wikimedia.org/wikipedia/commons/1/10/PyTorch_logo_icon.svg"
      proficiency: Experienced
      description: null

    - name: "Scikit-learn"
      logo: "https://upload.wikimedia.org/wikipedia/commons/0/05/Scikit-learn_logo_small.svg"
      proficiency: Fluent
      description: null

    - name: "Numpy"
      logo: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Keras_logo.svg"
      proficiency: Fluent
      description: null

  Language:
    - name: "English"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Fluent
      description: "Professional working proficiency."

    - name: "Chinese"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Elementary
      description: null
